version: '3.9'

services:
  db:
    image: postgres
    ports:
      - 5431:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shorturl